/* Generated By:JavaCC: Do not edit this line. HtmlConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETRA = 7;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 8;
  /** RegularExpression Id. */
  int EXTENSION = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETRA>",
    "<IDENTIFICADOR>",
    "<EXTENSION>",
    "\"<html>\"",
    "\"</html>\"",
    "\"<head\"",
    "\">\"",
    "\"</head>\"",
    "\"<title>\"",
    "\"</title>\"",
    "\"width=\\\"\"",
    "\"\\\", height=\\\"\"",
    "\"\\\"\"",
    "\"<body>\"",
    "\"</body>\"",
    "\"<layout rows=\"",
    "\" cols=\"",
    "\"</layout>\"",
    "\"<row>\"",
    "\"</row>\"",
    "\"<col>\"",
    "\"</col>\"",
    "\"<img \"",
    "\"src=\\\"\"",
    "\".\"",
    "\"..\"",
    "\"/\"",
    "\"alt=\\\"\"",
    "\"<label id=\\\"\"",
    "\"\\\" value=\\\"\"",
    "\"\\\" />\"",
    "\"<radioGroup>\"",
    "\"</radioGroup>\"",
    "\"<input type=\\\"radio\\\" id=\\\"\"",
    "\"\\\" name=\\\"\"",
    "\"\\\">\"",
    "\"</input>\"",
    "\"<select name = \\\"\"",
    "\"</select>\"",
    "\"<option value = \\\"\"",
    "\"</option>\"",
    "\"<table id=\\\"\"",
    "\"</table>\"",
    "\"<tr>\"",
    "\"</tr>\"",
    "\"<td>\"",
    "\"</td>\"",
    "\"<input type = \\\"text\\\" id =\\\"\"",
    "\"\\\" values = \\\"\"",
    "\"\\\"/>\"",
  };

}
