/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.caferrerb.drawer.vista;

import java.awt.Graphics;
import java.io.File;
import java.io.FileInputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringWriter;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.caferrerb.drawer.compilador.Compilador;
import org.caferrerb.drawer.vista.util.JCodeEditor;

/**
 *
 * @author caferrerb
 */
public class Ventana extends javax.swing.JFrame {
	private Compilador compilador;

	/**
	 * Creates new form Ventana
	 */
	public Ventana() {
		compilador = new Compilador();

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bEjecutar = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelDibujo = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        codigoEditor = new JCodeEditor();
        taError = new JCodeEditor();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolDerivacion = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemAbrir = new javax.swing.JMenuItem();
        mnuItemGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemEjecutar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bEjecutar.setText("Correr");
        bEjecutar.setFocusable(false);
        bEjecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEjecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEjecutarActionPerformed(evt);
            }
        });
        jToolBar1.add(bEjecutar);

        jSplitPane1.setDividerLocation(500);

        javax.swing.GroupLayout panelDibujoLayout = new javax.swing.GroupLayout(panelDibujo);
        panelDibujo.setLayout(panelDibujoLayout);
        panelDibujoLayout.setHorizontalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        panelDibujoLayout.setVerticalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(panelDibujo);

        jSplitPane3.setDividerLocation(300);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setTopComponent(codigoEditor);
        jSplitPane3.setRightComponent(taError);

        jSplitPane1.setLeftComponent(jSplitPane3);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        arbolDerivacion.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(arbolDerivacion);

        jMenu1.setText("Archivo");

        mnuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemAbrir.setText("Abrir");
        mnuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemAbrir);

        mnuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemGuardar.setText("Guardar");
        mnuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Run");

        menuItemEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemEjecutar.setText("Ejecutar");
        menuItemEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEjecutarActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEjecutar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void menuItemEjecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuItemEjecutarActionPerformed
		// TODO add your handling code here:
		run();
	}// GEN-LAST:event_menuItemEjecutarActionPerformed

	private void bEjecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bEjecutarActionPerformed
		// TODO add your handling code here:
		run();
	}// GEN-LAST:event_bEjecutarActionPerformed

	private void mnuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuItemAbrirActionPerformed
		// TODO add your handling code here:
		abrir();
	}// GEN-LAST:event_mnuItemAbrirActionPerformed

	private void mnuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuItemGuardarActionPerformed
		// TODO add your handling code here:
		guardar();
	}// GEN-LAST:event_mnuItemGuardarActionPerformed

	public void run() {
		// test();

		//Gestor g = Gestor.getInstance();
		//g.setG2d((Graphics2D) panelDibujo.getGraphics());

		String codigo = codigoEditor.getCodigo();
		taError.getTextArea().setText(codigo + "\n\n-----------");
		
		try {
			String salida=compilador.run(codigo);
			// taError.setText("OK\n"+codigo);

			//taError.getTextArea().setText(compilador.getCodigoExec());
			taError.getTextArea().append(salida.toString());
	        //arbolDerivacion.setModel(new DefaultTreeModel(compilador.getRaizDerivacion()));

		} catch (Exception e) {
			//taError.getTextArea().setText(compilador.getCodigoExec());

			StringWriter salida = new StringWriter();
			PrintWriter out = new PrintWriter(salida);
			e.printStackTrace(out);
			e.printStackTrace();
			taError.getTextArea().append(salida.toString());
		}
	}

	public void abrir() {
		JFileChooser choose = new JFileChooser();
		if (choose.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			File f = choose.getSelectedFile();
			try {
				FileInputStream input = new FileInputStream(f);
				byte[] data = new byte[(int) f.length()];
				input.read(data);
				codigoEditor.setCodigo(new String(data));

			} catch (Exception e) {
				StringWriter salida = new StringWriter();
				PrintWriter out = new PrintWriter(salida);
				e.printStackTrace(out);
				taError.getTextArea().setText(out.toString());
			}
		}
	}

	public void guardar() {
		JFileChooser choose = new JFileChooser();
		if (choose.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
			File f = choose.getSelectedFile();
			try {
				PrintStream salida = new PrintStream(f);
				salida.print(codigoEditor.getCodigo());
				JOptionPane.showInputDialog(null, "Guardado");

			} catch (Exception e) {
				StringWriter salida = new StringWriter();
				PrintWriter out = new PrintWriter(salida);
				e.printStackTrace(out);
				taError.getTextArea().setText(out.toString());
			}
		}
	}

	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ventana().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolDerivacion;
    private javax.swing.JButton bEjecutar;
    private JCodeEditor codigoEditor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuItemEjecutar;
    private javax.swing.JMenuItem mnuItemAbrir;
    private javax.swing.JMenuItem mnuItemGuardar;
    private javax.swing.JPanel panelDibujo;
    private JCodeEditor taError;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void paint(Graphics g) {
    	// TODO Auto-generated method stub
    	super.paint(g);
    }
}
